export const CHANGE_INPUT_VALUE = 'App/CHANGE_INPUT_VALUE';
export const CHANGE_SEARCH_ENGINE = 'App/CHANGE_SEARCH_ENGINE';
export const FETCH_RESULTS = 'App/FETCH_RESULTS';
export const FETCH_RESULTS_SUCCESS = 'App/FETCH_RESULTS_SUCCESS';
export const FETCH_RESULTS_ERROR = 'App/FETCH_RESULTS_ERROR';
export const CLEAR_RESULTS = 'App/CLEAR_RESULTS';
export const FETCH_RESULTS_PAGED = 'App/FETCH_RESULTS_PAGED';
